name: Build and deploy PHP app to Azure Web App - Pawnhub-Mobile-API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1FC4C848343B4B04B9B80B853580AB15 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BD9B3DCF4A3B4054B62CCEF49729463B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9E29AA90531749F5ACCDDB400438D4EE }}

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r mobile/* deploy/
          cp db.php deploy/
          if [ -d "certs" ]; then
            mkdir -p deploy/certs
            cp -r certs/* deploy/certs/
          fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pawnhub-mobile-api'
          package: deploy
